apiVersion: v1
kind: Service
metadata:
  name: naiara-agents-service-demo-svc
  namespace: demo
spec:
  selector:
    app: naiara-agents-service-demo
  ports:
    - protocol: TCP
      targetPort: 8000
      port: 8000
  type: NodePort
